config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "foods#index"

  root "public_recipes#index"
  resources :users, only: [:index] do
    resources :recipes
    resources :inventories
  end
  
  resources :public_recipes, only: [:index, :show]
  resources :foods, only:[:index,:new,:create,:destroy]

  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.nil?
      can :read, :all
    elsif user
      can %i[read create], :all
      can %i[destroy], Recipe, user_id: user.id
      can %i[destroy], Inventory, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :inventory_foods
  has_many :recipe_foods
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :inventory_foods
  belongs_to :user

  validates :name, presence: true, length: { in: 0..80 }
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :recipes
  has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def current_user
   User.find(params[:user_id])
 end
  # before_action :authenticate_user!
  #   before_action :configure_permitted_parameters, if: :devise_controller?

  #   protected

  #   def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_up, keys:
  #        %i[name email password password_confirmation])

  #   end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index]

  def index
    @foods = Food.all
  end

  def show; end

  def new
    @food = Food.new
  end

  def edit
    @food = Food.find(params[:id])
  end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  # def update
  #   respond_to do |format|
  #     if @food.update(food_params)
  #       format.html { redirect_to food_url(@food), notice: "Food was successfully updated." }
  #       format.json { render :show, status: :ok, location: @food }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @food.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
    def index 
        # @user = User.find(params[:user_id].to_i)
        # @inventory = @user.inventories
        @inventories = Inventory.all
    end

    def new
        @inventory = Inventory.new
    end

    def show 
    #    @inventory = Inventory.find(params[:id])
    #    @user = @inventory.user
         @foods = @inventory.inventory_foods.includes(:food)
    end

    def create 
        @inventory_new = current_user.inventories.new(inventory_params[:id])
        respond_to do |format|
           format.html do
            if @inventory_new.save
                redirect_to "/users/#{@inventory_new.user_id}/inventories/", notice: 'Inventory successfully created'
                else
                    redirect_to :new, alert: 'Error occured while creating a new inventory'
                end
            end
        end
    end

    private

    def inventory_params
        params.require(:inventory).permit(:name)
    end
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<tr id="<%= dom_id food %>">
  <th scope="row"> <%= food.id %> </th>
  <td>
    <%= food.name %>
  </td>

  <td>
    <%= food.measurement_unit %>
  </td>

  <td>
    <%= food.price %>
  </td>

  <td>
    <%= button_to "Delete", @food, method: :delete %>
  </td>

</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "New food", new_food_path %>
</div>

<table id="foods", class="table table-dark ms-5">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Food</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <%= render food %>
      
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/inventories/index.html.erb
<div class="container">
    <% if @inventories.empty? %>
    <h4>You have no inventories</h4>
    <%= link_to 'Add new inventory', new_user_inventory_path %>
       <% @inventories.each do |inventory| %>
    
    <div>
      <div>
        <h2>
           <%= link_to inventory.name, user_inventory_path(inventory.user_id, inventory)%>
        </h2>

        <% if can? :destory, inventory%>
            <%= button_to 'delete', user_inventory_path(inventory.user_id, inventory), method: :delete %>
        <% end %>
      </div>

      <p> Click on the inventory to see all kinds of foods in that particular inventory </p>
    </div>
        <% end %>
        
    <% end %>
</div>

app/views/inventories/new.html.erb
<div>
    <h3> Create a new inventory: </h3>
    <%= form_with model: @inventory, url: user_inventories_path, method: :post do |form| %>
        <div>
            <%= form.text_field :name, placeholder:'Inventory name' %>
        </div>
        
        <div>
            <%= form.submit 'Add new inventory' %> 
        </div>
    <% end %>
</div>

app/views/inventories/show.html.erb
<h1><%= @inventory.name %></h1>

<%= link_to 'Add food',"/inventory_foods/#{@inventory.id}/new" %>


<div>
    <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= button_to 'Delete', "/inventory_foods/#{@inventory.id}/destroy/#{food.id}", method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/inventory_foods/index.html.erb
<p>Inventory foods</p>

app/views/recipe_foods/index.html.erb
<p>Recipe foods</p>

app/views/recipes/index.html.erb
<p>Recipe</p>

app/views/users/index.html.erb
<p>Users</p>